title: "Bird Solutions"
baseline: "Digital solutions for small to medium-sized enterprises."
baseurl: https://thomascenni.com/
description: "Bird Solutions provides solutions for custom application development, deployment and maintenance."
author:
  name: Thomas Cenni
  url: https://thomascenni.com
static:
  exclude:
    - "main.js"
    - "main.scss"
    - "**/bulma-scss"
date:
  timezone: "Europe/Paris"
menus:
  main:
    - id: index
      enabled: false
googleanalytics: "UA-96532361-1"
